feat: create a reusable drawer for delete confirmation
Tascurator/tascurator-frontend pull request #159
Opened 2024-06-19 23:46 UTC by yuki-92c

## Overview

- I've implemented `delete confirmation` drawer components

## Changes

- created a file `src/components/ui/drawers/DeleteConfirmation.tsx`

## Review points

- [ ] Disable the Delete button when the checkbox is not checked
- [ ] Close the drawer by `Cancel` button 
- [ ] the component can perform dynamically with props

## Screenshots or videos

https://github.com/Tascurator/tascurator-frontend/assets/58718006/a350963a-0c61-436d-bea1-895bf22c213a

## Notes

- sample code

```ts

import {DeleteConfirmation } from '@/components/ui/drawers/DeleteConfirmation';
import { useState } from 'react';
import { Button } from '@/components/ui/button';

  const [isDrawerOpen, setIsDrawerOpen] = useState(false);
  const deleteItem = 'MY DELETE ITEM';

  return (
        <Button onClick={() => setIsDrawerOpen(true)}>Delete</Button>
        <DeleteConfirmation 
        deleteItem={deleteItem}
        open={isDrawerOpen} setOpen={setIsDrawerOpen}/>

```

## Assignee Checklist:

- [ ] The base branch is correct (no accidental merges)
- [ ] The branch name follows our branch naming rules
- [ ] The PR title follows our PR title rules
- [ ] My code follows our coding style
- [ ] I have commented on my code, particularly in hard-to-understand areas
- [ ] My changes generate no new warnings or errors in the console

## Reviewer Checklist:

- [ ] Code readability and simplicity
- [ ] Follows best practices and coding standards
- [ ] Understandable and maintainable code

2024-06-20 05:54 UTC, HrRn requested changes

2024-06-20 05:54 UTC, HrRn commented on src/components/ui/drawers/DeleteConfirmation.tsx
> +                variant={'secondary'}
Could you fix the button variant from secondary to outline?

2024-06-20 05:54 UTC, HrRn commented on src/components/ui/drawers/DeleteConfirmation.tsx
> +            <Checkbox
IMO, it would be better if the <p> tag could also be clicked using the <label> tag.

2024-06-20 17:03 UTC, Akikaze1119 commented
Could you please add 'Drawer' to the end of the file and component names?
DeleteConfirmation.tsx
　↓
DeleteConfirmationDrawer.tsx

2024-06-20 19:49 UTC, Akikaze1119 approved these changes
LGTM:)
Thank you!!

2024-06-21 18:35 UTC, HrRn approved these changes
LGTM :)

2024-06-21 18:40 UTC, merged