feat: integrate patch api into nameeditiondrawer
Tascurator/tascurator-frontend pull request #299
Opened 2024-07-28 00:04 UTC by yuki-92c

## Overview

- I implemented patch api into name edition drawer.

## Changes

- changed
`src/components/landlord-dashboard/LandlordDashboard.tsx`
`src/components/ui/accordion/AccordionCategoryItem.tsx`
`src/components/ui/drawers/NameEditionDrawer.tsx`
`src/components/ui/header.tsx`

## Review points

- Change Category/ Share house name
- Display a toast

## Screenshots or videos

-

https://github.com/user-attachments/assets/41726f18-2b41-41c9-9caa-22c28982fec1

## Notes

- The following sections need to be fixed.
  - When there are multiple categories/share houses, the modified ones move to the bottom of the list.
  - The header name on the share house detail page is hardcoded (I decided to address this in a separate PR after the implementation of the share house detail page is completed).

## Assignee Checklist:

- [ ] The base branch is correct (no accidental merges)
- [ ] The branch name follows our branch naming rules
- [ ] The PR title follows our PR title rules
- [ ] My code follows our coding style
- [ ] I have commented on my code, particularly in hard-to-understand areas
- [ ] My changes generate no new warnings or errors in the console

## Reviewer Checklist:

- [ ] Code readability and simplicity
- [ ] Follows best practices and coding standards
- [ ] Understandable and maintainable code

2024-07-28 01:19 UTC, akiomatic requested changes
Thank you. I've left some comments!

2024-07-28 01:19 UTC, akiomatic commented on src/components/ui/drawers/NameEditionDrawer.tsx
> +        console.log('Sharehouse ID:', shareHouseId);
Could you delete these console logging?

2024-07-28 01:19 UTC, akiomatic commented on src/components/ui/drawers/NameEditionDrawer.tsx
> +        console.log('Category ID:', categoryId);
Could you delete these console logs?

2024-07-28 01:19 UTC, akiomatic commented on src/components/ui/drawers/NameEditionDrawer.tsx
> - * const [open, setOpen] = useState(false);
Could you bring this back?

2024-07-28 01:19 UTC, akiomatic commented on src/components/ui/drawers/NameEditionDrawer.tsx
> +  categoryId?: string;
Could you modify this to accept only one ID, which will change dynamically based on the given `type`? For example, if `type` is `sharehouse`, the ID will be interpreted as `shareHouseId`.

2024-07-28 01:19 UTC, akiomatic commented on src/components/ui/drawers/NameEditionDrawer.tsx
>      // Submit the form data
This comment should be removed or moved to the correct position.

2024-07-28 01:19 UTC, akiomatic commented on src/components/ui/drawers/NameEditionDrawer.tsx
>    // TODO: Implement the onSubmit click functionality
Could you remove this TODO?

2024-07-28 01:19 UTC, akiomatic commented on src/components/ui/header.tsx
> +            sharehouseId={sharehouseId ?? ''}
Ideally, `sharehouseId` should **never be undefined** when the `type` is `HeaderItemWithDropdown`. I understand the issue mentioned in the PR description, so when addressing it, please ensure `sharehouseId` is always defined for `HeaderItemWithDropdown` type.

2024-07-28 03:13 UTC, yuki-92c commented
thanks Akio for reviewing. I modified the code so please check again

2024-07-28 03:19 UTC, yuki-92c commented
Thank you Akio. I fixed code so please check again.

2024-07-28 03:26 UTC, akiomatic requested changes
Thank you. Could you please check my comments and make some modifications?

2024-07-28 03:26 UTC, akiomatic commented on src/components/ui/drawers/NameEditionDrawer.tsx
> +  // categoryId?: string;
Could you remove the old props without commenting them out?

2024-07-28 03:26 UTC, akiomatic commented on src/components/ui/drawers/NameEditionDrawer.tsx
> +            shareHouseId: id!,
The non-null assertion could lead to unintended behavior later in development. Could you either add a comment on the line to remind us to fix it later or add an if statement to ensure the submission only happens if the ID is not null?

2024-07-28 03:26 UTC, akiomatic commented on src/components/ui/drawers/NameEditionDrawer.tsx
> +            categoryId: id!,
The non-null assertion could lead to unintended behavior later in development. Could you either add a comment on the line to remind us to fix it later or add an if statement to ensure the submission only happens if the ID is not null?

2024-07-28 03:26 UTC, akiomatic commented on src/components/ui/drawers/NameEditionDrawer.tsx
>    // TODO: Implement the onSubmit click functionality
Could you fix this too?

2024-07-28 03:26 UTC, akiomatic commented on src/components/ui/drawers/NameEditionDrawer.tsx
> +    formState: { errors, isValid, isSubmitting },
Could you remove `isValid` as you no longer use it?

2024-07-29 01:43 UTC, akiomatic approved these changes
Thank you! LGTM!

2024-07-29 04:42 UTC, merged