fix: revised zod schemas
Tascurator/tascurator-frontend pull request #340
Opened 2024-08-02 21:38 UTC by yuki-92c

## Overview

- I revised the zod schemas by adding trim and uuid to missing lines

## Changes

- add `.trim()` to string attributes
- add `.uuid()` to uuid attributes

## Assignee Checklist:

- [x] The base branch is correct (no accidental merges)
- [x] The branch name follows our branch naming rules
- [x] The PR title follows our PR title rules
- [x] My code follows our coding style
- [x] I have commented on my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings or errors in the console

## Reviewer Checklist:

- [ ] Code readability and simplicity
- [ ] Follows best practices and coding standards
- [ ] Understandable and maintainable code

2024-08-04 07:01 UTC, akiomatic requested changes
Thank you. Could you check my comments?

2024-08-04 07:01 UTC, akiomatic commented on src/constants/schema.ts
> +  email: z.string().email(ERROR_MESSAGES.EMAIL_INVALID).trim(),
The`.trim` should be before the `.email`.

2024-08-04 07:01 UTC, akiomatic commented on src/constants/schema.ts
> +  email: z.string().email(ERROR_MESSAGES.EMAIL_INVALID).trim(),
The`.trim` should be before the `.email`.

2024-08-04 07:01 UTC, akiomatic commented on src/constants/schema.ts
> +  email: z.string().email(ERROR_MESSAGES.EMAIL_INVALID).trim(),
The`.trim` should be before the `.email`.

2024-08-04 07:01 UTC, akiomatic commented on src/constants/schema.ts
> +  startDate: z.string().datetime().trim(),
The`.trim` should be before the `.datetime`.

2024-08-06 16:22 UTC, yuki-92c commented on src/constants/schema.ts
> +  startDate: z.string().datetime().trim(),
thank you for your review. I fixed according to the review so please check it again

2024-08-06 16:28 UTC, akiomatic approved these changes
Thank you. LGTM.

2024-08-06 16:42 UTC, merged