feat: add icons
Tascurator/tascurator-frontend pull request #38
Opened 2024-03-26 04:35 UTC by KaiKoide

## Overview

Add icons to be used for components to icons folder in public folder.
Path: `/public/assets/icons`

## Changes

- Add calendar icon
- Add check-circle icon
- Add check icon
- Add chevron-down icon
- Add chevron-right icon
- Add chevron-up icon
- Add edit icon
- Add eye-close icon
- Add eye-open icon
- Add home icon
- Add info icon 
- Add logout icon
- Add mail icon
- Add menu-meatball icon
- Add pen icon
- Add plus-circle icon
- Add plus icon
- Add profile icon
- Add trash icon
- Add user icon
- Add users icon

## Screenshots or videos

The images of icons in Figma
<img width="322" alt="image" src="https://github.com/Tascurator/tascurator-frontend/assets/144519746/9f9c581a-324f-4a57-9a12-17ce287e5c94">

## Assignee Checklist:

- [ ] The base branch is correct (no accidental merges)
- [ ] The branch name follows our branch naming rules
- [ ] The PR title follows our PR title rules
- [ ] My code follows our coding style
- [ ] I have commented on my code, particularly in hard-to-understand areas
- [ ] My changes generate no new warnings or errors in the console

## Reviewer Checklist:

- [ ] Code readability and simplicity
- [ ] Follows best practices and coding standards
- [ ] Understandable and maintainable code

2024-03-26 08:01 UTC, akiomatic requested changes
I noticed one thing that might need to be addressed, so I would like you to take a look at it!

2024-03-26 08:01 UTC, akiomatic commented on public/assets/icons/profile.svg
I think it's unnecessary to add this `profile.svg` since it can be easily created by using the [Avatar component](https://github.com/Tascurator/tascurator-frontend/pull/36) with the `user.svg`.

2024-03-27 03:00 UTC, KaiKoide commented on public/assets/icons/profile.svg
Thank you for your review! I've removed the profile icon:)

2024-03-27 03:02 UTC, akiomatic approved these changes
LGTM.

2024-03-30 19:55 UTC, yuki-92c approved these changes
LGTM, Thank you.

2024-04-01 18:42 UTC, merged