feat: create UI components steps indicator
Tascurator/tascurator-frontend pull request #57
Opened 2024-04-09 23:56 UTC by Akikaze1119

## Overview
The task is to create a shared UI component for `steps indicator`.

## Changes
Created `steps indicator` component based on [figma](https://www.figma.com/file/5tNJDDfqC0HnHbWygzEXiL/Tascurator?type=design&node-id=0-1&mode=design&t=SvzFH1RdR9OWCQRn-0)

## Screenshots or videos
▼Figma
![Screenshot 2024-04-09 at 4 49 07 PM](https://github.com/Tascurator/tascurator-frontend/assets/132441773/435f563f-ccda-4725-a373-b6c0f479623d)

▼Code
https://github.com/Tascurator/tascurator-frontend/assets/132441773/7ce8df02-e98a-4420-8c11-84dc2ec22c69

## Notes
### About bar style
I used hard code for setting the height of the horizontal bar.
- Figma: 2px
- Code: h-[0.125rem](=2px)
*Note: The minimum height of the Tailwind class is `h-1 (4px)`, which is too long for the bar.

### About the name
Since 'stepper' seems to be more common, both the file name and the component name are set to 'stepper'.
[Reference](https://mui.com/material-ui/react-stepper/)

### About the confirmation code
The following code can be used for review.
```
'use client';
import { useState } from 'react';

import { Stepper } from '@/components/ui/stepper';
import { Button } from '@/components/ui/button';

const INITIAL_STEP = 1;
const MAX_STEPS = 4;

export default function Home() {
  const [currentStep, setCurrentStep] = useState(INITIAL_STEP);

  return (
    <>
      <main className="flex min-h-screen flex-col items-center p-6">
        <Stepper currentStep={currentStep} maxSteps={MAX_STEPS} />

        <div className="flex mt-10 gap-4">
          <Button
            size="sm"
            onClick={() => setCurrentStep((prev) => prev - 1)}
            disabled={currentStep === INITIAL_STEP}
          >
            Previous
          </Button>
          <Button
            size="sm"
            onClick={() => setCurrentStep((prev) => prev + 1)}
            disabled={currentStep === MAX_STEPS}
          >
            Next
          </Button>
        </div>
      </main>
    </>
  );
}
```

## Assignee Checklist:

- [ ] The base branch is correct (no accidental merges)
- [ ] The branch name follows our branch naming rules
- [ ] The PR title follows our PR title rules
- [ ] My code follows our coding style
- [ ] I have commented on my code, particularly in hard-to-understand areas
- [ ] My changes generate no new warnings or errors in the console

## Reviewer Checklist:

- [ ] Code readability and simplicity
- [ ] Follows best practices and coding standards
- [ ] Understandable and maintainable code

2024-04-25 09:01 UTC, KaiKoide requested changes

2024-04-25 09:01 UTC, KaiKoide commented on src/components/ui/stepper.tsx
> +const Stepper: React.FC<IStep> = ({ currentStep, maxSteps }: IStep) => {
Could you add TSDoc so the other team members could apply this component? The way to write TSDoc can be confirmed on Scrapbox.

2024-04-25 09:01 UTC, KaiKoide commented on src/components/ui/stepper.tsx
> +      <div className="flex justify-between relative before:bg-slate-300 before:absolute before:h-[0.125rem] before:top-1/2 before:transform-y-1/2 before:w-full before:left-0">
The font-weight is 500 so could you add `font-medium`?
<img width="623" alt="image" src="https://github.com/Tascurator/tascurator-frontend/assets/144519746/4db374f3-2273-479f-a2c2-9d40019b25fa">

2024-04-26 19:15 UTC, Akikaze1119 commented
@KaiKoide 
Thank you for your review!
I modified codes.

2024-04-26 20:51 UTC, KaiKoide approved these changes
Thank you for the correction! LGTM 👍

2024-04-26 21:15 UTC, merged