feat: create UI components accordion
Tascurator/tascurator-frontend pull request #62
Opened 2024-04-12 08:04 UTC by yuki-92c

## Overview

- Add accordion component in the components/ui folder based on the design on Figma.

## Changes

- Install checkbox component from shadcn/ui
    - https://ui.shadcn.com/docs/components/accordion
- Style the design

## Review points

- The styling matches the Figma design

## Screenshots or videos

- figma UI component ( landlord )
<img width="372" alt="image" src="https://github.com/Tascurator/tascurator-frontend/assets/58718006/b2aae239-d899-429d-bf9c-f78dcaec3c6a">

- figma mockup ( tenant )
<img width="341" alt="image" src="https://github.com/Tascurator/tascurator-frontend/assets/58718006/81940aa6-16ec-4005-a131-c933bd46b95f">

- accordion component 
<img width="669" alt="image" src="https://github.com/Tascurator/tascurator-frontend/assets/58718006/da37c017-9adc-4fcc-accc-7450bc253dee">

## Notes

- The contents of the accordion differs from landlord and tenant. Tenant's page needs date.
- To display date you have to set `scheduleDate` as a prop.

- sample code
```ts
import {
  Accordion,
  AccordionContent,
  AccordionItem,
  AccordionTrigger,
} from "@/components/ui/accordion"
import { CircleEllipsis, Ellipsis } from "lucide-react"

export default function Home() {
  return (
    <main className="flex min-h-screen flex-col items-center justify-between pt-32">
      <div className="z-10 max-w-5xl w-full items-center justify-between font-mono text-sm lg:flex">
        <Accordion type="single" collapsible className="w-full">
        <AccordionItem value="item-1">
          <AccordionTrigger scheduleDate={"12/01-12/07"}>Bathroom
          <CircleEllipsis className='ml-4'/> 
          </AccordionTrigger >
          <AccordionContent>
            <div className="flex">
              <div className='items-center'>
                <div className="text-lg font-medium">mop the floor</div>
                <p className="leading-7 text-sm [&:not(:first-child)]:mt-3">
                  The king, seeing how much happier his subjects were, realized the error of
                  his ways and repealed the joke tax.
                </p>
              </div>
              <Ellipsis className='h-4 w-4 shrink-0 transition-transform duration-200 ml-auto' />
            </div>
          </AccordionContent>
          <AccordionContent>
            <div className="flex">
              <div className='items-center'>
                <div className="text-lg font-medium">mop the floor</div>
                <p className="leading-7 text-sm [&:not(:first-child)]:mt-3">
                  The king, seeing how much happier his subjects were, realized the error of
                  his ways and repealed the joke tax.
                </p>
              </div>
              <Ellipsis className='h-4 w-4 shrink-0 transition-transform duration-200 ml-auto' />
            </div>
          </AccordionContent>
        </AccordionItem>
        <AccordionItem value="item-2">
          <AccordionTrigger>Kitchen</AccordionTrigger>
          <AccordionContent>
            Yes. It comes with default styles that matches the other
            components&apos; aesthetic.
          </AccordionContent>
        </AccordionItem>
      </Accordion>
      </div>
    </main>
  );
}

```

## Assignee Checklist:

- [x] The base branch is correct (no accidental merges)
- [x] The branch name follows our branch naming rules
- [x] The PR title follows our PR title rules
- [x] My code follows our coding style
- [x] I have commented on my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings or errors in the console

## Reviewer Checklist:

- [ ] Code readability and simplicity
- [ ] Follows best practices and coding standards
- [ ] Understandable and maintainable code

2024-04-28 00:24 UTC, KaiKoide requested changes

2024-04-28 00:24 UTC, KaiKoide commented on src/components/ui/accordion.tsx
> +      {scheduleDate && (
The gap between the date and the icon is `6px`.
<img width="500" alt="image" src="https://github.com/Tascurator/tascurator-frontend/assets/144519746/3e9be360-d1d2-4de1-8453-72f380331cc1">

2024-04-28 00:24 UTC, KaiKoide commented on src/components/ui/accordion.tsx
> +        <p className="text-sm leading-7 text-gray-500">{scheduleDate}</p>
The font color is `#333333`.
<img width="580" alt="image" src="https://github.com/Tascurator/tascurator-frontend/assets/144519746/d112876c-64b8-4da1-96dc-d7792dc96a27">

2024-04-28 00:24 UTC, KaiKoide commented on src/components/ui/accordion.tsx
> +   */
Could you please move the TSDoc comment above `const Accordion = Root;` so you can see the content when you hover the line?
<img width="727" alt="image" src="https://github.com/Tascurator/tascurator-frontend/assets/144519746/0e10957c-52f9-4535-bf04-f2f43c83f151">

2024-04-29 06:19 UTC, KaiKoide approved these changes
Thank you for your work! LGTM 👍

2024-04-30 21:00 UTC, KaiKoide reviewed
Could you execute `npm install` just in case?

2024-05-01 01:29 UTC, yuki-92c commented
thanks! and execute `npm install` so please review when you have time

2024-05-01 03:50 UTC, KaiKoide approved these changes
Thank you! LGTM 👍

2024-05-01 06:02 UTC, merged