Feature/4 install linter formatter
Tascurator/tascurator-frontend pull request #9
Opened 2024-03-07 13:51 UTC by KaiKoide

## Overview

To facilitate smooth development, set up the linter and formatter to main consistent code quality in the Next.js + TypeScript development environment.

## Changes

- [x] Install [Prettier](https://prettier.io/)
- [x] Install [CommitLint](https://commitlint.js.org/)
- [x] Install [Lint-staged](https://github.com/lint-staged/lint-staged#readme)
- [x] Install [Husky](https://typicode.github.io/husky/)
- [x] Configure Prettier
- [x] Configure ESLint
- [x] Configure CommitLint
- [x] Configure pre-commit hooks to make it run these linter & formatter checks after a commit is made, with Husky and Lint-staged
 
## Assignee Checklist:

- [x] The base branch is correct (no accidental merges)
- [x] The branch name follows our branch naming rules
- [x] The PR title follows our PR title rules
- [x] My code follows our coding style
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings or errors in the console

## Reviewer Checklist

- [x] The code will be formatted before committing
- [x] Invalid commit messages cannot be committed

2024-03-07 23:13 UTC, akiomatic commented
Could you change the PR title to the appropriate one?

2024-03-07 23:36 UTC, akiomatic requested changes
Thank you for setting up the linter & formatter, but I kindly ask you to take a look at my comments.

2024-03-07 23:36 UTC, akiomatic commented on package.json
>    },
I'd like you to revise the pre-commit script to run ESLint checks as well as Prettier checks.

2024-03-07 23:36 UTC, akiomatic commented on package.json
> +    "format-ignore-path": "prettier . --write --ignore-path {any file}",
I'd like you to add scripts to run ESLint checks like `lint:fix` that fixes ESLint errors automatically.

2024-03-07 23:36 UTC, akiomatic commented on .prettierignore
Could you add the following to avoid unnecessary formatting?

```
node_modules/
.next/
```

2024-03-08 05:14 UTC, KaiKoide commented on package.json
> +    "format-ignore-path": "prettier . --write --ignore-path {any file}",
I add `"lint:fix": "eslint --fix ."` to `package.json`.

2024-03-08 07:01 UTC, KaiKoide commented on package.json
>    },
I add `lint:fix` in `package.json`.

2024-03-08 07:02 UTC, KaiKoide commented on .prettierignore
I updated `.prettierignore`.

2024-03-08 07:12 UTC, akiomatic approved these changes
LGTM!
Thank you for setting up!

2024-03-08 08:10 UTC, Akikaze1119 approved these changes
Thank you!
I've done some testing and it looks fine.

2024-03-08 08:13 UTC, HrRn approved these changes
Thank you!

2024-03-08 16:42 UTC, merged